// Ths module is included in the following assembly:
//
// assembly_using-openshift-pipelines.adoc

[id="defining-and-creating-pipelineresources_{context}"]
= Defining and creating pipeline resources

`PipelineResources` are artifacts that are used as inputs to a `Task` and can be output by a `Task`.

[discrete]
== Procedure
After you create `Task` s, create `PipelineResources` that contain the specifics of the Git repository and the image registry to be used in the `Pipeline` during execution as follows:

. Copy the content of the following sample `PipelineResource` YAML file that defines the Git repository and reference for the PetClinic application and save it.
+
----
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petclinic-git
spec:
  type: git
  params:
  - name: url
    value: https://github.com/spring-projects/spring-petclinic
----

. Create the petclininc-git `PipelineResource`:
+
----
oc create -f petclininc-git.yaml
----

. Copy the content of the following sample `PipelineResource` YAML file that defines the OpenShift internal registry to which you want to push the PetClinic image and save it.
+
----
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petclinic-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/spring-petclinic
Create the petclinic-image pipelineresource:
oc create -f petclininc-git.yaml
----

. Create the petclininc-image `PipelineResource`:
+
----
oc create -f petclininc-image.yaml
----

////
[discrete]
== Additional resources

* A bulleted list of links to other material closely related to the contents of the procedure module.
* For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
