#!/usr/bin/env bash
set -e -u -o pipefail

declare -r SCRIPT_DIR=$(cd -P $(dirname $0) && pwd)

declare -r NAMESPACE=${NAMESPACE:-pipelines-tutorial}

_log() {
    local level=$1; shift
    echo -e "$level: $@"
}


log.err() {
    _log "ERROR" "$@" >&2
}

info() {
    _log "\nINFO" "$@"
}

err() {
    local code=$1; shift
    local msg="$@"; shift
    log.err $msg
    exit $code
}

valid_command() {
  local fn=$1; shift
  [[ $(type -t "$fn") == "function" ]]
}

execute() {
  echo "Running:  '$@'"
  ${DRY_RUN:-false} || "$@"
}

#mask oc and tkn to use the $NAMESPACE
OC() {
  oc -n ${NAMESPACE} "$@"
}

TKN() {
 tkn -n ${NAMESPACE} "$@"
}

demo.validate() {
  tkn version >/dev/null 2>&1 || err 1 "no tkn binary found"
  oc version >/dev/null 2>&1 || err 1 "no oc binary found"
  return 0
}

demo.prep() {
  demo.validate
  oc get ns "$NAMESPACE" 2>/dev/null  || {
    oc new-project $NAMESPACE
  }

  OC get sa pipeline || OC create serviceaccount pipeline
  OC adm policy add-scc-to-user privileged -z pipeline
  OC adm policy add-role-to-user edit -z pipeline
}

declare -r TEKTON_CATALOG="https://raw.githubusercontent.com/tektoncd/catalog/master"
declare -r OPENSHIFT_CATALOG="https://raw.githubusercontent.com/openshift/pipelines-catalog/master"
declare -r TASKS_DIR=tmp/tasks

declare -r OC_TASK="$TEKTON_CATALOG/openshift-client/openshift-client-task.yaml"
declare -r LOCAL_OC_TASK="$TASKS_DIR/oc.task.yaml"

declare -r S2I_JAVA8_TASK="$OPENSHIFT_CATALOG/s2i-java-8/s2i-java-8-task.yaml"
declare -r LOCAL_S2I_JAVA8_TASK="$TASKS_DIR/s2i-java8.task.yaml"

demo.get-tasks() {
  echo Downloading tasks from catalog into $TASKS_DIR directory
  mkdir -p "$TASKS_DIR"
  curl -sLf  "$S2I_JAVA8_TASK" -o "$LOCAL_S2I_JAVA8_TASK"
  curl -sLf  "$OC_TASK" -o "$LOCAL_OC_TASK"
}


demo.setup() {
  demo.get-tasks

  info "Apply petclinic resources"
  OC apply -f resources/petclinic.yaml

  info "Apply pipeline tasks"
  OC apply -f "$TASKS_DIR"

  info "Applying resources"
  OC apply -f resources/petclinic-resources.yaml

  info "Applying pipeline"
  OC apply -f resources/petclinic-deploy-pipeline.yaml

  echo -e "\nPipeline"
  echo "==============="
  TKN p desc petclinic-deploy-pipeline
}

demo.logs() {
  TKN pipeline logs petclinic-deploy-pipeline -l -f
}

demo.run() {
  TKN pipeline start petclinic-deploy-pipeline \
    -r app-git=petclinic-git \
    -r app-image=petclinic-image \
    -s pipeline

  sleep 5
  demo.logs
}

demo.help() {
  cat <<-EOF
		USAGE:
		  demo [command]

		COMMANDS:
		  prep      creates project and service account
		  setup     creates tasks, pipeline and resources
		  run       starts pipeline
EOF

}


main() {
  local fn="demo.${1:-help}"
  valid_command "$fn" || {
    demo.help
    err  1 "invalid command '$1'"
  }

  cd $SCRIPT_DIR
  $fn "$@"
  return $?
}

main "$@"
